### ISSUE TITLE
Multiple assignments don't work

### ISSUE THREAD

**Issue by hishamhm** [titan-lang/titan-v0#102]
This is different from supporting multiple returns in functions.

Test case:
```lua
-- this works
function f()
   local x = 1
   local y = 2
end
-- this doesn't
function g()
   local x, y = 1, 2
end
```

**Comment by gligneul** [comment]
This is not even contemplated in the parser yet, so I assume it is considered a enhancement.

**Comment by hishamhm** [comment]
WIP in #104

**Comment by hishamhm** [comment]
Implemented by @mascarenhas!
