### ISSUE TITLE
Update Lpeglabel to version 1.5

### ISSUE THREAD

**Issue by hugomg** [titan-lang/titan-v0#118]
Lpeglabel 1.5 introduced some breaking changes to its API. Titan's parser will need to be updated to take advantage of the new and improved API.

http://lua-users.org/lists/lua-l/2018-02/msg00162.html

**Comment by hishamhm** [comment]
Pinging @sqmedeiros :)

**Comment by sqmedeiros** [comment]
Hi :-)
I think I can handle this issue.

**Comment by hugomg** [comment]
Done! :)
