### ISSUE TITLE
Confusing rockspec file names

### ISSUE THREAD

**Issue by hugomg** [titan-lang/titan-v0#57]
The name of our rockspec file is `titan-v0-scm-1.rockspec` but the name that appears in the README instructions is `titan-lang-scm-1.rockspec`. And to add to the confusion we also just renamed the repository to titan instead of titan-v0.

What should the new name of the rockspec file be? Should we rename the old rockspecs or only update the name in the new rockspecs we create?

**Comment by hishamhm** [comment]
I'd say lets

**Comment by hishamhm** [comment]
ouch, typing from the phone. Can we use just titan? We don't have rockspecs published in luarocks.org yet, right? So changing the name shouldn't be a big deal. Sorry for not checking all occurrences of titan-v0 when I marked the switch as done!

**Comment by andremm** [comment]
No, we haven’t published the rockspec yet. So I guess using only titan is fine/enough.
