### ISSUE TITLE
Parser should store source locations in the generated syntax tree

### ISSUE THREAD

**Issue by hugomg** [titan-lang/titan-v0#6]

**Comment by andremm** [comment]
I opened an [issue](https://github.com/vsbenas/parser-gen/issues/4) asking how we can do this with `parser-gen`.

**Comment by andremm** [comment]
I created PR #24 to add source locations in the AST so we can use them to generate type error messages with line and column number. There might be some bugs with the position of if statements and expressions, but I believe that we can solve them along with the type checker test cases.

**Comment by hishamhm** [comment]
Closing this one, since we have source positions in the tree now, and it's easy to get lines and columns.
