### ISSUE TITLE
Pretty-printer doesn't understand comments

### ISSUE THREAD

**Issue by hugomg** [titan-lang/titan-v0#93]
The C files our compiler is currently generating are terribly indented because it is not recognizing open braces that are followed by comments. In cases such as the following, it continues at the same indentation level instead of increasing the indentation level by one.

    if (path == NULL) { /* no environment variable? */

A possible workaround would be to change our style guide to require that comments appear in lines by themselves. A more technical solution would be to make the reindent_c function a bit more clever.

What do you think would be the best course of action here?

**Comment by hishamhm** [comment]
I'd go the simple way and just move the comments. Making the pretty-printer fully comment-aware would require a full blown C lexer. The pretty-printer already makes other major assumptions about the way the code generator produces code, so comments are just another one.

**Comment by hugomg** [comment]
OK, I am taking care of this.

**Comment by gligneul** [comment]
@hugomg Another option is to use only `//` comments, they will be easier to pretty print.

**Comment by hugomg** [comment]
Are we trying to be strictly ANSI-C compatible?

**Comment by gligneul** [comment]
I prefer to maintain ANSI-C compatibility, but we are already using the `--std=c99` flag in `titanc`.

**Comment by gligneul** [comment]
If you don't want to waste a lot of cycles with this I think moving the comments is the best option.
