### ISSUE TITLE
Don't allow declarations with basic type names

### ISSUE THREAD

**Issue by gligneul** [titan-lang/titan-v0#98]
The program bellow shouldn't be valid in Titan:
```
function integer()
end
```

**Comment by hishamhm** [comment]
This has been fixed, right?

**Comment by hugomg** [comment]
Well spotted!

This is currently fixed in master and we also have [test cases](https://github.com/titan-lang/titan/blob/9dddd13af8e68118c41bd6564ce62075b5207149/spec/parser_spec.lua#L745) for it.

**Comment by hishamhm** [comment]
Sweet! :)
